# Generated by Django 2.0.3 on 2018-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.DateTimeField(verbose_name='Date added')),
                ('logo', models.CharField(max_length=254)),
            ],
        ),
    ]
