# Generated by Django 2.0.3 on 2018-03-24 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date added'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crypto',
            name='short_name',
            field=models.CharField(max_length=20),
        ),
    ]
